### ISSUE TITLE
Node 4 (LTS) and Node 6 (LTS) compatibility

### ISSUE THREAD

**Issue by Redsandro** [eye3/nkit4nodejs#3]
On a quest to parse big XML quicker, I stumbled across this interesting package, and was quick to try to benchmark it. But it wouldn't build on Node 4.

After inspecting previous issues, I discovered this module only supports node 0.11 by using a compatibility layer on top of 0.8, unless I'm mistaken.

If this thing is really faster than any parser out there, it's quite a gem. Any chance to get this building on Node 4 LTS (and Node 6 soon following as LTS)?

```
$ npm install --save nkit4nodejs
npm WARN package.json xml2js-tester@0.2.1 No repository field.
npm WARN package.json xml2js-tester@0.2.1 No README data
\
> nkit4nodejs@2.4.2 install /var/www/sites/interseismic/tests/xml4/node_modules/nkit4nodejs
> node-gyp rebuild

make: Entering directory '/var/www/sites/interseismic/tests/xml4/node_modules/nkit4nodejs/build'
  CC(target) Release/obj.target/expat/deps/expat-2.1.0/lib/xmlparse.o
  CC(target) Release/obj.target/expat/deps/expat-2.1.0/lib/xmltok.o
  CC(target) Release/obj.target/expat/deps/expat-2.1.0/lib/xmlrole.o
  AR(target) Release/obj.target/deps/libexpat.a
  COPY Release/libexpat.a
  CXX(target) Release/obj.target/nkit/deps/nkit/src/constants.o
  CXX(target) Release/obj.target/nkit/deps/nkit/src/tools.o
  CXX(target) Release/obj.target/nkit/deps/nkit/src/dynamic/dynamic.o
  CXX(target) Release/obj.target/nkit/deps/nkit/src/dynamic/dynamic_json.o
  CXX(target) Release/obj.target/nkit/deps/nkit/src/dynamic/dynamic_path.o
  CXX(target) Release/obj.target/nkit/deps/nkit/src/dynamic/dynamic_table.o
  CXX(target) Release/obj.target/nkit/deps/nkit/src/dynamic/dynamic_table_index_comparators.o
  CXX(target) Release/obj.target/nkit/deps/nkit/src/dynamic/dynamic_xml.o
  CXX(target) Release/obj.target/nkit/deps/nkit/src/logger/rotate_logger.o
  CXX(target) Release/obj.target/nkit/deps/nkit/src/encoding/transcode.o
  CXX(target) Release/obj.target/nkit/deps/nkit/src/xml/xml2var.o
  CXX(target) Release/obj.target/nkit/deps/nkit/3rd/netbsd/strptime.o
  AR(target) Release/obj.target/deps/libnkit.a
  COPY Release/libnkit.a
  CC(target) Release/obj.target/yajl/deps/yajl-2.0.5/src/yajl_lex.o
  CC(target) Release/obj.target/yajl/deps/yajl-2.0.5/src/yajl_encode.o
  CC(target) Release/obj.target/yajl/deps/yajl-2.0.5/src/yajl_parser.o
  CC(target) Release/obj.target/yajl/deps/yajl-2.0.5/src/yajl_version.o
  CC(target) Release/obj.target/yajl/deps/yajl-2.0.5/src/yajl_alloc.o
  CC(target) Release/obj.target/yajl/deps/yajl-2.0.5/src/yajl_buf.o
  CC(target) Release/obj.target/yajl/deps/yajl-2.0.5/src/yajl_tree.o
  CC(target) Release/obj.target/yajl/deps/yajl-2.0.5/src/yajl_gen.o
  CC(target) Release/obj.target/yajl/deps/yajl-2.0.5/src/yajl.o
  AR(target) Release/obj.target/deps/libyajl.a
  COPY Release/libyajl.a
  CXX(target) Release/obj.target/nkit4nodejs/src/nkit4nodejs_module.o
In file included from ../src/nkit4nodejs_module.cpp:17:0:
../deps/nan/nan.h: In function ‘v8::Local<v8::Signature> NanNew(v8::Handle<v8::FunctionTemplate>, int, v8::Handle<v8::FunctionTemplate>*)’:
../deps/nan/nan.h:189:78: error: no matching function for call to ‘v8::Signature::New(v8::Isolate*, v8::Handle<v8::FunctionTemplate>&, int&, v8::Handle<v8::FunctionTemplate>*&)’
     return v8::Signature::New(v8::Isolate::GetCurrent(), receiver, argc, argv);
                                                                              ^
In file included from /home/redsandro/.node-gyp/4.2.6/include/node/node.h:42:0,
                 from ../deps/nan/nan.h:23,
                 from ../src/nkit4nodejs_module.cpp:17:
/home/redsandro/.node-gyp/4.2.6/include/node/v8.h:4675:27: note: candidate: static v8::Local<v8::Signature> v8::Signature::New(v8::Isolate*, v8::Local<v8::FunctionTemplate>)
   static Local<Signature> New(
                           ^
/home/redsandro/.node-gyp/4.2.6/include/node/v8.h:4675:27: note:   candidate expects 2 arguments, 4 provided
In file included from ../src/nkit4nodejs_module.cpp:17:0:
../deps/nan/nan.h: At global scope:
../deps/nan/nan.h:271:3: error: redefinition of ‘v8::Local<T> NanNew(P) [with T = v8::StringObject; P = v8::Local<v8::String>]’
   NanNew<v8::StringObject, v8::Handle<v8::String> >(
   ^
../deps/nan/nan.h:264:3: note: ‘v8::Local<T> NanNew(P) [with T = v8::StringObject; P = v8::Local<v8::String>]’ previously declared here
   NanNew<v8::StringObject, v8::Local<v8::String> >(
   ^
../deps/nan/nan.h:289:36: error: redefinition of ‘template<class T> v8::Local<v8::RegExp> NanNew(v8::Local<v8::String>, v8::RegExp::Flags)’
   NAN_INLINE v8::Local<v8::RegExp> NanNew(
                                    ^
../deps/nan/nan.h:283:36: note: ‘template<class T> v8::Local<v8::RegExp> NanNew(v8::Handle<v8::String>, v8::RegExp::Flags)’ previously declared here
   NAN_INLINE v8::Local<v8::RegExp> NanNew(
                                    ^
../deps/nan/nan.h:301:36: error: redefinition of ‘template<class T, class P> v8::Local<v8::RegExp> NanNew(v8::Local<v8::String>, v8::RegExp::Flags)’
   NAN_INLINE v8::Local<v8::RegExp> NanNew(
                                    ^
../deps/nan/nan.h:295:36: note: ‘template<class T, class P> v8::Local<v8::RegExp> NanNew(v8::Handle<v8::String>, v8::RegExp::Flags)’ previously declared here
   NAN_INLINE v8::Local<v8::RegExp> NanNew(
                                    ^
../deps/nan/nan.h:481:19: error: ‘NanNew’ declared as an ‘inline’ variable
       v8::String::ExternalAsciiStringResource *resource) {
                   ^
../deps/nan/nan.h:481:19: warning: ‘always_inline’ attribute ignored [-Wattributes]
../deps/nan/nan.h:481:19: error: ‘v8::Local<v8::String> NanNew’ redeclared as different kind of symbol
../deps/nan/nan.h:475:36: note: previous declaration ‘v8::Local<v8::String> NanNew(v8::String::ExternalStringResource*)’
   NAN_INLINE v8::Local<v8::String> NanNew(
                                    ^
../deps/nan/nan.h:481:7: error: ‘ExternalAsciiStringResource’ is not a member of ‘v8::String’
       v8::String::ExternalAsciiStringResource *resource) {
       ^
../deps/nan/nan.h:481:48: error: ‘resource’ was not declared in this scope
       v8::String::ExternalAsciiStringResource *resource) {
                                                ^
../deps/nan/nan.h:495:27: error: redefinition of ‘template<class T> v8::Local<T> _NanEscapeScopeHelper(v8::Local<T>)’
   NAN_INLINE v8::Local<T> _NanEscapeScopeHelper(v8::Local<T> val) {
                           ^
../deps/nan/nan.h:490:27: note: ‘template<class T> v8::Local<T> _NanEscapeScopeHelper(v8::Handle<T>)’ previously declared here
   NAN_INLINE v8::Local<T> _NanEscapeScopeHelper(v8::Handle<T> val) {
                           ^
../deps/nan/nan.h:755:13: error: ‘node::smalloc’ has not been declared
     , node::smalloc::FreeCallback callback
             ^
../deps/nan/nan.h:755:35: error: expected ‘,’ or ‘...’ before ‘callback’
     , node::smalloc::FreeCallback callback
                                   ^
../deps/nan/nan.h: In function ‘v8::Local<v8::Object> NanNewBufferHandle(char*, size_t, int)’:
../deps/nan/nan.h:759:50: error: ‘callback’ was not declared in this scope
         v8::Isolate::GetCurrent(), data, length, callback, hint);
                                                  ^
../deps/nan/nan.h:759:60: error: ‘hint’ was not declared in this scope
         v8::Isolate::GetCurrent(), data, length, callback, hint);
                                                            ^
../deps/nan/nan.h: In function ‘v8::Local<v8::Object> NanNewBufferHandle(const char*, uint32_t)’:
../deps/nan/nan.h:766:67: error: no matching function for call to ‘New(v8::Isolate*, const char*&, uint32_t&)’
     return node::Buffer::New(v8::Isolate::GetCurrent(), data, size);
                                                                   ^
In file included from ../deps/nan/nan.h:24:0,
                 from ../src/nkit4nodejs_module.cpp:17:
/home/redsandro/.node-gyp/4.2.6/include/node/node_buffer.h:31:40: note: candidate: v8::MaybeLocal<v8::Object> node::Buffer::New(v8::Isolate*, v8::Local<v8::String>, node::encoding) <near match>
 NODE_EXTERN v8::MaybeLocal<v8::Object> New(v8::Isolate* isolate,
                                        ^
/home/redsandro/.node-gyp/4.2.6/include/node/node_buffer.h:31:40: note:   conversion of argument 3 would be ill-formed:
In file included from ../src/nkit4nodejs_module.cpp:17:0:
../deps/nan/nan.h:766:67: error: invalid conversion from ‘uint32_t {aka unsigned int}’ to ‘node::encoding’ [-fpermissive]
     return node::Buffer::New(v8::Isolate::GetCurrent(), data, size);
                                                                   ^
In file included from ../deps/nan/nan.h:24:0,
                 from ../src/nkit4nodejs_module.cpp:17:
/home/redsandro/.node-gyp/4.2.6/include/node/node_buffer.h:43:40: note: candidate: v8::MaybeLocal<v8::Object> node::Buffer::New(v8::Isolate*, char*, size_t) <near match>
 NODE_EXTERN v8::MaybeLocal<v8::Object> New(v8::Isolate* isolate,
                                        ^
/home/redsandro/.node-gyp/4.2.6/include/node/node_buffer.h:43:40: note:   conversion of argument 2 would be ill-formed:
In file included from ../src/nkit4nodejs_module.cpp:17:0:
../deps/nan/nan.h:766:67: error: invalid conversion from ‘const char*’ to ‘char*’ [-fpermissive]
     return node::Buffer::New(v8::Isolate::GetCurrent(), data, size);
                                                                   ^
../deps/nan/nan.h: In function ‘v8::Local<v8::Object> NanNewBufferHandle(uint32_t)’:
../deps/nan/nan.h:770:29: error: could not convert ‘node::Buffer::New(v8::Isolate::GetCurrent(), ((size_t)size))’ from ‘v8::MaybeLocal<v8::Object>’ to ‘v8::Local<v8::Object>’
     return node::Buffer::New(v8::Isolate::GetCurrent(), size);
                             ^
../deps/nan/nan.h: In function ‘v8::Local<v8::Object> NanBufferUse(char*, uint32_t)’:
../deps/nan/nan.h:777:12: error: ‘Use’ is not a member of ‘node::Buffer’
     return node::Buffer::Use(v8::Isolate::GetCurrent(), data, size);
            ^
../deps/nan/nan.h: In function ‘bool _NanGetExternalParts(v8::Handle<v8::Value>, const char**, size_t*)’:
../deps/nan/nan.h:2103:12: error: ‘class v8::String’ has no member named ‘IsExternalAscii’
   if (str->IsExternalAscii()) {
            ^
../deps/nan/nan.h:2104:23: error: ‘ExternalAsciiStringResource’ in ‘class v8::String’ does not name a type
     const v8::String::ExternalAsciiStringResource* ext;
                       ^
../deps/nan/nan.h:2105:5: error: ‘ext’ was not declared in this scope
     ext = str->GetExternalAsciiStringResource();
     ^
../deps/nan/nan.h:2105:16: error: ‘class v8::String’ has no member named ‘GetExternalAsciiStringResource’
     ext = str->GetExternalAsciiStringResource();
                ^
nkit4nodejs.target.mk:106: recipe for target 'Release/obj.target/nkit4nodejs/src/nkit4nodejs_module.o' failed
make: *** [Release/obj.target/nkit4nodejs/src/nkit4nodejs_module.o] Error 1
make: Leaving directory '/var/www/sites/interseismic/tests/xml4/node_modules/nkit4nodejs/build'
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/home/redsandro/.nvm/versions/node/v4.2.6/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:270:23)
gyp ERR! stack     at emitTwo (events.js:87:13)
gyp ERR! stack     at ChildProcess.emit (events.js:172:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:200:12)
gyp ERR! System Linux 4.4.0-53-generic
gyp ERR! command "/home/redsandro/.nvm/versions/node/v4.2.6/bin/node" "/home/redsandro/.nvm/versions/node/v4.2.6/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /var/www/sites/interseismic/tests/xml4/node_modules/nkit4nodejs
gyp ERR! node -v v4.2.6
gyp ERR! node-gyp -v v3.0.3
gyp ERR! not ok 
npm ERR! Linux 4.4.0-53-generic
npm ERR! argv "/home/redsandro/.nvm/versions/node/v4.2.6/bin/node" "/home/redsandro/.nvm/versions/node/v4.2.6/bin/npm" "install" "--save" "nkit4nodejs"
npm ERR! node v4.2.6
npm ERR! npm  v2.14.12
npm ERR! code ELIFECYCLE

npm ERR! nkit4nodejs@2.4.2 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the nkit4nodejs@2.4.2 install script 'node-gyp rebuild'.
npm ERR! This is most likely a problem with the nkit4nodejs package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get their info via:
npm ERR!     npm owner ls nkit4nodejs
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /var/www/sites/interseismic/tests/xml4/npm-debug.log
```

**Comment by eye3** [comment]
Hi, Sander!

I'll try to fix it soon, but I can not tell you exactly when, because I have not enough free time now.

**Comment by Redsandro** [comment]
Ok, I'm looking forward to checking it out when you find the time to fix
the build. :)

**Comment by eye3** [comment]
Hi, Sander!

I fixed this issue. Could you please take last version 2.4.3 and check it on your platform?

npm install nkit4nodejs@2.4.3

**Comment by Redsandro** [comment]
Hi @eye3, thanks! :+1: 

This is pretty fast! I will verify output at a later time and see if it misses anything.

PS - It's not fair to compare to one of the slow pure-js solutions.

Personally I use `xml2js-expat` for translation. And `nkit` is *1.5 times faster!*

Rapidx2j is even faster. [I've been attempting](https://github.com/damirn/rapidx2j/issues/14) to get `rapidx2j` to be an inline replacement, but it still doesn't support parsing the way I like.

However, in my preliminary testing, you place second. I can't believe these fast(er) parsers are not more pupular.

xml parser olympics
---
_Random big xml file_

Rank | Module | Time
---|---|---
1\. | `rapidx2j` | 210 ms
2\. | `nkit` | 290 ms
3\. | `xml2js-expat` | 440 ms
----
